id: IEE55C63E
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-31T12:18:44+00:00'
last_modified: '2022-06-09T04:57:54.092055+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W30385
  title: སུམ་རྟགས་སྐོར་གྱི་དཔེ་རྒྱུན་དཀོན་པོ་འགའ་ཕྱོགས་གཅིག་ཏུ་བསྒྲིགས་པ་མུ་ཏིག་ཕྲེང་བ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    24A6:
      image_group_id: I1PD28038
      title: Volume 1 of sum rtags skor gyi dpe rgyun dkon po 'ga' phyogs gcig tu
        bsgrigs pa mu tig phreng ba
      total_pages: 354
      order: 1
      base_file: 24A6.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
