id: P007107
initial_creation_type: ocr
source_metadata:
  id: bdr:W30385
  title: སུམ་རྟགས་སྐོར་གྱི་དཔེ་རྒྱུན་དཀོན་པོ་འགའ་ཕྱོགས་གཅིག་ཏུ་བསྒྲིགས་པ་མུ་ཏིག་ཕྲེང་བ
  author: ''
  volumes:
    65a07639250741f9a5b983036883c8a5:
      image_group_id: I1PD28038
      title: ''
      volume_number: 1
      total_pages: 354
ebook_metadata:
  title: སུམ་རྟགས་སྐོར་གྱི་དཔེ་རྒྱུན་དཀོན་པོ་འགའ་ཕྱོགས་གཅིག་ཏུ་བསྒྲིགས་པ་མུ་ཏིག་ཕྲེང་བ
  author: ''
  sku: P007107
  cover: cover.jpg
  layers:
  - pagination
