id: opecha:P007107
initial_creation_type: ocr
source_metadata:
  id: bdr:W30385
  title: སུམ་རྟགས་སྐོར་གྱི་དཔེ་རྒྱུན་དཀོན་པོ་འགའ་ཕྱོགས་གཅིག་ཏུ་བསྒྲིགས་པ་མུ་ཏིག་ཕྲེང་བ
  volume:
    019d34dc71b442c3af81a0213129113b:
      image_group_id: I1PD28038
      title: Volume 1 of sum rtags skor gyi dpe rgyun dkon po 'ga' phyogs gcig tu
        bsgrigs pa mu tig phreng ba
      volume_number: 1
      total_pages: 354
  author: ''
ebook_metadata:
  title: སུམ་རྟགས་སྐོར་གྱི་དཔེ་རྒྱུན་དཀོན་པོ་འགའ་ཕྱོགས་གཅིག་ཏུ་བསྒྲིགས་པ་མུ་ཏིག་ཕྲེང་བ
  author: ''
  sku: P007107
  cover: cover.jpg
  layers:
  - pagination
